version: '3.8'

services: 

  app:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - '8080'
    deploy:
      replicas: 4
    networks:
      - front-network


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    depends_on:
    - app
    networks:
      - front-network


networks:
  front-network:
    driver: bridge